### ISSUE TITLE
I have some problems with read pixel

### ISSUE THREAD

**Issue by panzahahaha** [obstruse/ThermalCamera#1]
Thank you for your kindness.
I used your code with MLX90640 so I changed the import value to "SMBus" and then they said I have some problem with line 222 in heat.py 

AttributeError: type object 'SMBus' has no attribute 'readPixels'

What should I do? Could you help me please

**Comment by obstruse** [comment]
I've never used the MLX90640, but it looks like it would work really well for this project. (unfortunately, out of stock at the moment).  

Depends on which MLX90640 library you're using:  The Adafruit library uses 'getFrame(frame)' instead of 'readPixels()'; PiMoroni and others use 'frame = get_frame()'.  Have you run the library example test programs?  Compare the sensor setup and read calls to see the differences.  Unfortunately without a MLX90640 to test with, I don't know what problems you might encounter.

**Comment by panzahahaha** [comment]
Thank you for your help. I will try your suggestion.

**Comment by obstruse** [comment]
Well, I finally got around to implementing it on MLX90640...
