### ISSUE TITLE
cam calibration

### ISSUE THREAD

**Issue by natxopedreira** [obstruse/ThermalCamera#2]
Hello
Can you please elaborate the calibration process to put heat data over rgb image?

Also not need to consider displacement of one sensor to another? i mean not in the same physical position, just trying to understand how this works

Thank you!!

**Comment by obstruse** [comment]
Yes, camera offset is a problem, especially at short distance (parallax).  Using a small USB camera helps reduce that offset.  Also, depending on how you mount things, the two sensors are probably not lying perfectly flat - you'll need to twist them a little so that they're both pointing in the same direction.

The heat sensor (AMG8833) has approximately 55 degree FOV; use a protractor to find the largest angle that is visible in the camera.  The python will use those two angles to scale the heat image to match the camera image (if camera FOV < heat FOV), or scale the camera image to match the heat image (if camera FOV > heat FOV).

**Comment by natxopedreira** [comment]
It makes sense, thank you for the explain. 

Can i ask how good is the calibration using that method? i was thinking in trying to do an opencv calibration (my thermal sensor is 160x120) but i can not make my head arround on how to do that calibration with that low resolution, thats why im asking about your method.

Thanks a lot!!

**Comment by obstruse** [comment]
It works good enough... although the low resolution of the AMG8833 makes "good enough" an easy target to hit.  160x120 resolution should work well, just measure FOV for both sensors and scale them to match.  Maybe add some fine-tuning of the scale/offset to get the images to line up...

**Comment by natxopedreira** [comment]
Thank you, i will try!
